# Generated by Django 5.1.1 on 2024-09-08 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
