# Generated by Django 5.1.1 on 2024-09-09 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_remove_team_project_team_projects_alter_team_workers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="projects",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="task.project"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
