# Generated by Django 5.1.1 on 2024-09-09 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0006_alter_team_projects_alter_team_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
