# Generated by Django 5.1.1 on 2024-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0007_project_workers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
    ]
