# Generated by Django 5.1.1 on 2024-09-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0008_alter_project_options_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed"]},
        ),
    ]
