# Generated by Django 5.1.1 on 2024-09-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0009_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "priority"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["username", "first_name", "last_name"]},
        ),
    ]
